-- H2 2.3.232;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT '4422b93bbe4d2e43' HASH '499d67c5934c2643923f39d4eb370a1cd14ab4a4d71825618fd96cf010df8f40' ADMIN;         
CREATE SEQUENCE "PUBLIC"."ENTITY_SEQUENCE" START WITH 100 INCREMENT BY 50;    
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_REPAIR_TYPES"(
    "ACTIVE" BOOLEAN,
    "ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "DESCRIPTION" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);           
ALTER TABLE "PUBLIC"."HTE_REPAIR_TYPES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("RN_");            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_REPAIR_TYPES;        
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_USERS"(
    "ACTIVE" BOOLEAN,
    "ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "EMAIL" CHARACTER VARYING(255),
    "FIRST_NAME" CHARACTER VARYING(255),
    "LAST_NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "PHONE" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255),
    "AUTHORITY" ENUM('ADMIN', 'CUSTOMER')
);        
ALTER TABLE "PUBLIC"."HTE_USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("RN_");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_USERS;               
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_DELIVERY_INFO"(
    "ACTIVE" BOOLEAN,
    "ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "ADDRESS" CHARACTER VARYING(255),
    "POSTAL_CODE" CHARACTER VARYING(255)
);       
ALTER TABLE "PUBLIC"."HTE_DELIVERY_INFO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("RN_");           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_DELIVERY_INFO;       
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_DEVICE_TYPES"(
    "ACTIVE" BOOLEAN,
    "ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "IMAGE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
); 
ALTER TABLE "PUBLIC"."HTE_DEVICE_TYPES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("RN_");            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_DEVICE_TYPES;        
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_MODELS"(
    "ACTIVE" BOOLEAN,
    "BRAND_ID" INTEGER,
    "DEVICE_TYPE_ID" INTEGER,
    "ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "NAME" CHARACTER VARYING(255)
);    
ALTER TABLE "PUBLIC"."HTE_MODELS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("RN_");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_MODELS;              
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_BRANDS"(
    "ACTIVE" BOOLEAN,
    "ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "IMAGE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);       
ALTER TABLE "PUBLIC"."HTE_BRANDS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("RN_");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_BRANDS;              
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_ORDERS"(
    "ACTIVE" BOOLEAN,
    "DELIVERY_INFO_ID" INTEGER,
    "ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "STATUS" INTEGER,
    "USER_ID" INTEGER,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "ORDER_NUMBER" UUID
);      
ALTER TABLE "PUBLIC"."HTE_ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_87" PRIMARY KEY("RN_"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_ORDERS;              
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_STATUS"(
    "ACTIVE" BOOLEAN,
    "ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "STATUS" CHARACTER VARYING(20)
);           
ALTER TABLE "PUBLIC"."HTE_STATUS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8E" PRIMARY KEY("RN_"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_STATUS;              
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_REPAIRS"(
    "ACTIVE" BOOLEAN,
    "ID" INTEGER,
    "MODEL_ID" INTEGER,
    "REPAIR_TYPE_ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "PRICE" FLOAT(53),
    "UPDATED_AT" TIMESTAMP(6)
);               
ALTER TABLE "PUBLIC"."HTE_REPAIRS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("RN_"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_REPAIRS;             
CREATE MEMORY TABLE "PUBLIC"."BRANDS"(
    "ACTIVE" BOOLEAN,
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "IMAGE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE "PUBLIC"."BRANDS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_754" PRIMARY KEY("ID");     
-- 14 +/- SELECT COUNT(*) FROM PUBLIC.BRANDS; 
INSERT INTO "PUBLIC"."BRANDS" VALUES
(TRUE, 1, NULL, NULL, '/images/brands/apple.svg', 'Apple'),
(TRUE, 2, NULL, NULL, '/images/brands/samsung.svg', 'Samsung'),
(TRUE, 3, NULL, NULL, '/images/brands/huawei.svg', 'Huawei'),
(TRUE, 4, NULL, NULL, '/images/brands/bq.png', 'BQ'),
(TRUE, 5, NULL, NULL, '/images/brands/google.svg', 'Google'),
(TRUE, 6, NULL, NULL, '/images/brands/htc.png', 'HTC'),
(TRUE, 7, NULL, NULL, '/images/brands/lg.svg', 'LG'),
(TRUE, 8, NULL, NULL, '/images/brands/motorola.svg', 'Motorola'),
(TRUE, 9, NULL, NULL, '/images/brands/nokia.svg', 'Nokia'),
(TRUE, 10, NULL, NULL, '/images/brands/oneplus.svg', 'OnePlus'),
(TRUE, 11, NULL, NULL, '/images/brands/Oppo.svg', 'Oppo'),
(TRUE, 12, NULL, NULL, '/images/brands/sony.svg', 'Sony'),
(TRUE, 13, NULL, NULL, '/images/brands/xiaomi.svg', 'Xiaomi'),
(TRUE, 14, NULL, NULL, '/images/brands/zte.png', 'ZTE');   
CREATE MEMORY TABLE "PUBLIC"."DELIVERY_INFO"(
    "ACTIVE" BOOLEAN,
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "ADDRESS" CHARACTER VARYING(255) NOT NULL,
    "POSTAL_CODE" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."DELIVERY_INFO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DELIVERY_INFO;           
CREATE MEMORY TABLE "PUBLIC"."DEVICE_TYPES"(
    "ACTIVE" BOOLEAN,
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "IMAGE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255) NOT NULL
);          
ALTER TABLE "PUBLIC"."DEVICE_TYPES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID"); 
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.DEVICE_TYPES;            
INSERT INTO "PUBLIC"."DEVICE_TYPES" VALUES
(TRUE, 1, NULL, NULL, '/images/devices-types/movil.svg', U&'M\00f3vil'),
(TRUE, 2, NULL, NULL, '/images/devices-types/tablet.svg', 'Tablet'),
(TRUE, 3, NULL, NULL, '/images/devices-types/laptop.svg', U&'Port\00e1til'),
(TRUE, 4, NULL, NULL, '/images/devices-types/electrical.svg', U&'Electrodom\00e9sticos');           
CREATE MEMORY TABLE "PUBLIC"."MODELS"(
    "ACTIVE" BOOLEAN,
    "BRAND_ID" INTEGER,
    "DEVICE_TYPE_ID" INTEGER NOT NULL,
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "NAME" CHARACTER VARYING(255) NOT NULL
);    
ALTER TABLE "PUBLIC"."MODELS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_87D" PRIMARY KEY("ID");     
-- 15 +/- SELECT COUNT(*) FROM PUBLIC.MODELS; 
INSERT INTO "PUBLIC"."MODELS" VALUES
(TRUE, 1, 1, 1, NULL, NULL, 'iPhone 13'),
(TRUE, 2, 1, 2, NULL, NULL, 'Galaxy S21'),
(TRUE, 1, 2, 3, NULL, NULL, 'iPad Pro'),
(TRUE, 3, 1, 4, NULL, NULL, 'Modelo Huawei'),
(TRUE, 4, 1, 5, NULL, NULL, 'Modelo BQ'),
(TRUE, 5, 1, 6, NULL, NULL, 'Modelo Google'),
(TRUE, 6, 1, 7, NULL, NULL, 'Modelo HTC'),
(TRUE, 7, 1, 8, NULL, NULL, 'Modelo LG'),
(TRUE, 8, 1, 9, NULL, NULL, 'Modelo Motorola'),
(TRUE, 9, 1, 10, NULL, NULL, 'Modelo Nokia'),
(TRUE, 10, 1, 11, NULL, NULL, 'Modelo OnePlus'),
(TRUE, 11, 1, 12, NULL, NULL, 'Modelo Oppo'),
(TRUE, 12, 1, 13, NULL, NULL, 'Modelo Sony'),
(TRUE, 13, 1, 14, NULL, NULL, 'Modelo Xiaomi'),
(TRUE, 14, 1, 15, NULL, NULL, 'Modelo ZTE');          
CREATE MEMORY TABLE "PUBLIC"."ORDER_REPAIRS"(
    "ORDER_ID" INTEGER NOT NULL,
    "REPAIR_ID" INTEGER NOT NULL
);         
ALTER TABLE "PUBLIC"."ORDER_REPAIRS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_EC" PRIMARY KEY("ORDER_ID", "REPAIR_ID");            
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_REPAIRS;           
INSERT INTO "PUBLIC"."ORDER_REPAIRS" VALUES
(1, 1),
(1, 2),
(2, 3);        
CREATE MEMORY TABLE "PUBLIC"."ORDERS"(
    "ACTIVE" BOOLEAN,
    "DELIVERY_INFO_ID" INTEGER,
    "ID" INTEGER NOT NULL,
    "STATUS" INTEGER NOT NULL,
    "USER_ID" INTEGER,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "ORDER_NUMBER" UUID NOT NULL
);      
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8B7" PRIMARY KEY("ID");     
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.ORDERS;  
INSERT INTO "PUBLIC"."ORDERS" VALUES
(TRUE, NULL, 1, 4, 1, NULL, NULL, UUID '550e8400-e29b-41d4-a716-446655440000'),
(TRUE, NULL, 2, 5, 2, NULL, NULL, UUID '550e8400-e29b-41d4-a716-446655440001');        
CREATE MEMORY TABLE "PUBLIC"."REPAIR_TYPES"(
    "ACTIVE" BOOLEAN,
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "DESCRIPTION" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."REPAIR_TYPES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ID"); 
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.REPAIR_TYPES;            
INSERT INTO "PUBLIC"."REPAIR_TYPES" VALUES
(TRUE, 1, NULL, NULL, 'Replace cracked or broken screen', 'Screen Replacement'),
(TRUE, 2, NULL, NULL, 'Replace degraded battery', 'Battery Replacement');       
CREATE MEMORY TABLE "PUBLIC"."REPAIRS"(
    "ACTIVE" BOOLEAN,
    "ID" INTEGER NOT NULL,
    "MODEL_ID" INTEGER,
    "PRICE" FLOAT(53),
    "REPAIR_TYPE_ID" INTEGER,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6)
); 
ALTER TABLE "PUBLIC"."REPAIRS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6C" PRIMARY KEY("ID");     
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.REPAIRS; 
INSERT INTO "PUBLIC"."REPAIRS" VALUES
(TRUE, 1, 1, 129.99, 1, NULL, NULL),
(TRUE, 2, 2, 89.99, 2, NULL, NULL),
(TRUE, 3, 2, 99.99, 1, NULL, NULL);         
CREATE MEMORY TABLE "PUBLIC"."STATUS"(
    "ACTIVE" BOOLEAN,
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "STATUS" CHARACTER VARYING(20)
);             
ALTER TABLE "PUBLIC"."STATUS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_92" PRIMARY KEY("ID");      
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.STATUS;  
INSERT INTO "PUBLIC"."STATUS" VALUES
(TRUE, 1, NULL, NULL, 'PENDING'),
(TRUE, 2, NULL, NULL, 'COLLECTING'),
(TRUE, 3, NULL, NULL, 'BEING_REPAIRED'),
(TRUE, 4, NULL, NULL, 'DELIVERING'),
(TRUE, 5, NULL, NULL, 'COMPLETED'),
(TRUE, 6, NULL, NULL, 'CANCELLED');       
CREATE MEMORY TABLE "PUBLIC"."USERS"(
    "ACTIVE" BOOLEAN,
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "EMAIL" CHARACTER VARYING(255),
    "FIRST_NAME" CHARACTER VARYING(255),
    "LAST_NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "PHONE" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255),
    "AUTHORITY" ENUM('ADMIN', 'CUSTOMER')
);          
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D4" PRIMARY KEY("ID");      
-- 28 +/- SELECT COUNT(*) FROM PUBLIC.USERS;  
INSERT INTO "PUBLIC"."USERS" VALUES
(TRUE, 1, NULL, NULL, 'admin.doe@example.com', 'Admin', 'Doe', '$2a$12$4fnrlDgI.2x/loBfQU1x/.rgqtZzeadcc7IuQXhPQ3AhldZoz4yhe', '123456789', 'admin1', 'ADMIN'),
(TRUE, 2, NULL, NULL, 'john.doe@example.com', 'John', 'Doe', '$2a$12$LMDEs/diT2q1mZlfrix49ulvNYZdI0KvV/LR9yh.oux5xLjOsNJZi', '123456789', 'user1', 'CUSTOMER'),
(TRUE, 3, NULL, NULL, 'john3@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe3', 'CUSTOMER'),
(TRUE, 4, NULL, NULL, 'john4@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe4', 'CUSTOMER'),
(TRUE, 5, NULL, NULL, 'john5@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe5', 'CUSTOMER'),
(TRUE, 6, NULL, NULL, 'john6@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe6', 'CUSTOMER'),
(TRUE, 7, NULL, NULL, 'john7@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe7', 'CUSTOMER'),
(TRUE, 8, NULL, NULL, 'john8@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe8', 'CUSTOMER'),
(TRUE, 9, NULL, NULL, 'john9@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe9', 'CUSTOMER'),
(TRUE, 10, NULL, NULL, 'john10@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe10', 'CUSTOMER'),
(TRUE, 11, NULL, NULL, 'john11@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe11', 'CUSTOMER'),
(TRUE, 12, NULL, NULL, 'john12@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe12', 'CUSTOMER'),
(TRUE, 13, NULL, NULL, 'john13@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe13', 'CUSTOMER'),
(TRUE, 14, NULL, NULL, 'john14@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe14', 'CUSTOMER'),
(TRUE, 15, NULL, NULL, 'john15@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe15', 'CUSTOMER'),
(TRUE, 16, NULL, NULL, 'john16@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe16', 'CUSTOMER'),
(TRUE, 17, NULL, NULL, 'john17@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe17', 'CUSTOMER'),
(TRUE, 18, NULL, NULL, 'john18@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe18', 'CUSTOMER'),
(TRUE, 19, NULL, NULL, 'john19@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe19', 'CUSTOMER'),
(TRUE, 20, NULL, NULL, 'john20@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe20', 'CUSTOMER'),
(TRUE, 21, NULL, NULL, 'john21@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe21', 'CUSTOMER'),
(TRUE, 22, NULL, NULL, 'john22@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe22', 'CUSTOMER'),
(TRUE, 23, NULL, NULL, 'john23@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe23', 'CUSTOMER'),
(TRUE, 24, NULL, NULL, 'john24@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe24', 'CUSTOMER'),
(TRUE, 25, NULL, NULL, 'john25@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe25', 'CUSTOMER'),
(TRUE, 26, NULL, NULL, 'john26@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe26', 'CUSTOMER'),
(TRUE, 27, NULL, NULL, 'john27@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe27', 'CUSTOMER'),
(TRUE, 28, NULL, NULL, 'john28@example.com', 'John', 'Doe', 'password', '123456789', 'john_doe28', 'CUSTOMER');    
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8B" UNIQUE NULLS DISTINCT ("ORDER_NUMBER"); 
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" UNIQUE NULLS DISTINCT ("EMAIL");          
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" UNIQUE NULLS DISTINCT ("USERNAME");      
ALTER TABLE "PUBLIC"."BRANDS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_75" UNIQUE NULLS DISTINCT ("NAME");         
ALTER TABLE "PUBLIC"."MODELS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_87DE" UNIQUE NULLS DISTINCT ("BRAND_ID", "DEVICE_TYPE_ID", "NAME");         
ALTER TABLE "PUBLIC"."MODELS" ADD CONSTRAINT "PUBLIC"."FK95S72G5HNSL3O0BQEUHNOKDXU" FOREIGN KEY("BRAND_ID") REFERENCES "PUBLIC"."BRANDS"("ID") ON DELETE CASCADE NOCHECK;     
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."FK32QL8UBNTJ5UH44PH9659TIIH" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."ORDER_REPAIRS" ADD CONSTRAINT "PUBLIC"."FKPV0OTRO7W0GXFUUAUOO04N2WU" FOREIGN KEY("ORDER_ID") REFERENCES "PUBLIC"."ORDERS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REPAIRS" ADD CONSTRAINT "PUBLIC"."FKFGOOVHS84B9SIEPRIY83NYYDQ" FOREIGN KEY("REPAIR_TYPE_ID") REFERENCES "PUBLIC"."REPAIR_TYPES"("ID") ON DELETE CASCADE NOCHECK;        
ALTER TABLE "PUBLIC"."MODELS" ADD CONSTRAINT "PUBLIC"."FKAQWM7L2WW42CJYQUA8Q6C44IK" FOREIGN KEY("DEVICE_TYPE_ID") REFERENCES "PUBLIC"."DEVICE_TYPES"("ID") ON DELETE CASCADE NOCHECK;         
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."FKOG5C4DEWAXRG2D0TPKLULVCA2" FOREIGN KEY("DELIVERY_INFO_ID") REFERENCES "PUBLIC"."DELIVERY_INFO"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."REPAIRS" ADD CONSTRAINT "PUBLIC"."FKEY98NOLPHSX1U5RHLLK42SIUP" FOREIGN KEY("MODEL_ID") REFERENCES "PUBLIC"."MODELS"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."FK4ADKD09GXMRP46OHI2OQC0Q2H" FOREIGN KEY("STATUS") REFERENCES "PUBLIC"."STATUS"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."ORDER_REPAIRS" ADD CONSTRAINT "PUBLIC"."FKB52Y130IWWF7LC84WUIIP0COQ" FOREIGN KEY("REPAIR_ID") REFERENCES "PUBLIC"."REPAIRS"("ID") NOCHECK;              
