version: "3.9"

services:
  db:
    image: postgres:16
    container_name: relogic_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: relogic_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
    ports:
      - "${SPRING_PORT}:8080"
    restart: always
    volumes:
      - ./images:/app/images

  frontend:
    build: ./frontend
    container_name: relogic_frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      PORT: ${NEXT_PORT}
    ports:
      - "${NEXT_PORT}:3000"
    restart: always

volumes:
  db_data:
