# H2 Database Configuration
spring.application.name=${DATABASE_APPLICATION_NAME}
spring.h2.console.enabled=${DATABASE_ENABLED}
spring.h2.console.path=${DATABASE_PATH}

spring.sql.init.mode=${DATABASE_INIT_MODE}

# JPA
spring.jpa.hibernate.ddl-auto=${JPA_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
spring.jpa.defer-datasource-initialization=${JPA_DEFER_DATASOURCE_INITIALIZATION}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration= ${JWT_EXPIRATION}
jwt.issuer=${JWT_ISSUER}
