spring.application.name=relogic
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# JWT
jwt.secret=8iD44SjORG6gosXkkbLWOdzJP0jSFzzNjlpMvaMZNGpIwk5RZE5hOthKWsC1y30qKbyyVr3YBsLGmAIgc5iMUMcUvm1fEWX6O7R7WlnkVXkp6hrY4EGJIkbIBLoGrC4xAYd36Ff8qLxJXlZgxOkAi7z1DIkaeMUjFnSgTCtRbr2yaLCi9Q2yZLkgDhhXDJprJzHzodaHEk98NmiXNn6TjDj92h8FQ4ifvsEpcmWoMzrCs95yHFV8g4t39rfbKcqk
jwt.expiration= 7200000
jwt.issuer=ReLogic
