# H2 Database Configuration
# spring.application.name=${DATABASE_APPLICATION_NAME}
# spring.h2.console.enabled=${DATABASE_ENABLED}
# spring.h2.console.path=${DATABASE_PATH}

# spring.sql.init.mode=${DATABASE_INIT_MODE}

# === Configuración de base de datos ===
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=${DATABASE_DRIVER}


# JPA
spring.jpa.hibernate.ddl-auto=${JPA_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
spring.jpa.defer-datasource-initialization=${JPA_DEFER_DATASOURCE_INITIALIZATION}
spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Habilitar multipart
spring.servlet.multipart.enabled=true

# Limite de tamaño por archivo y por request
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Carpeta pública adicional
spring.web.resources.static-locations=classpath:/static/,file:images/

# Carpeta de subida relativa a la raíz del proyecto
app.upload-dir=images
# En producción, por ejemplo:
# upload.dir=/var/www/relogic/images

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration= ${JWT_EXPIRATION}
jwt.issuer=${JWT_ISSUER}
